version: '3'
services:
  imalive_zookeeper:
    image: "confluentinc/cp-zookeeper"
    hostname: imalive_zookeeper
    container_name: imalive_zookeeper
    ports:
      - 32181:32181
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181


  imalive_kafka:
    image: confluentinc/cp-kafka
    hostname: imalive_kafka
    container_name: imalive_kafka
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - imalive_zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=imalive_zookeeper:32181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:29092,PLAINTEXT://imalive_kafka:9092
      - KAFKA_BROKER_ID=1

  imalive_postgresql:
    image: postgres
    hostname: imalive_postgres
    container_name: imalive_postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=imalive
      - POSTGRES_USER=docker
      - POSTGRES_HOST_AUTH_METHOD=trust
    logging:
      driver: none
